
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 60
#define YY_END_OF_BUFFER 61
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[274] =
    {   0,
        0,    0,   61,   59,    2,    1,   59,   59,   50,   59,
       43,   44,   49,   46,   40,   47,   38,   48,   36,   42,
       41,   53,   51,   54,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   57,
       58,   59,    2,    1,    0,    0,    4,    0,    0,    4,
       39,    3,    0,   36,   45,   55,   52,   56,    0,   33,
       33,   33,    0,    0,   33,   33,    0,   33,    0,   21,
       21,   33,   33,    0,   33,   33,    0,   18,   33,   18,
       33,    0,    6,    8,    6,   33,    0,   33,    0,   33,
       23,   33,   23,   33,    0,   33,   33,    0,    0,    0,

        6,    0,    0,    0,   21,    8,    6,    0,    0,   39,
       39,    3,    0,    7,    7,   33,    0,    0,    0,    7,
       33,    0,   33,    0,    0,   33,    0,   33,    0,   33,
        0,   27,   27,   27,   33,    0,   17,   17,   17,   12,
       12,    9,    9,   33,    0,   33,    0,   33,    0,   33,
        0,    0,   11,   11,   33,    0,   33,    0,    0,   11,
        0,    0,    7,    7,    9,    0,    0,    0,   11,    9,
        7,   37,   33,    0,    0,   34,   33,    0,   33,    0,
        0,   15,   15,   33,    0,   19,   19,   33,    0,   33,
        0,   33,    0,   30,   14,   14,   30,   14,   20,   20,

       31,   31,   20,   33,    0,   33,    0,    0,   14,   15,
        0,   31,   14,    0,   19,   14,   20,   14,   25,   25,
       34,   26,   26,   33,    0,   26,   33,    0,   32,   32,
       33,    0,   33,    0,   24,   24,   28,   28,   24,    0,
       25,    0,   24,   24,   24,   33,    0,   22,   22,   33,
        0,   33,    0,   33,    0,   22,    0,    0,    0,   22,
       16,   16,   13,   13,   10,   10,   29,   29,   10,   10,
       16,   10,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    1,    6,    1,    1,    7,    1,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   19,   20,   21,
       22,   23,    1,    1,   24,   25,   26,   27,   28,   29,
       30,   31,   32,   33,   33,   34,   35,   36,   37,   38,
       33,   39,   40,   41,   42,   43,   44,   33,   45,   33,
       46,    1,   47,    1,   48,    1,   24,   25,   26,   27,

       49,   29,   30,   31,   32,   33,   33,   34,   35,   36,
       37,   38,   33,   50,   40,   41,   42,   43,   44,   33,
       45,   33,    1,   51,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[52] =
    {   0,
        1,    1,    2,    1,    3,    4,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    3,    1,    1,
        1,    1,    1,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    5,    1,    5,    3,    3,
        5
    } ;

static const flex_int16_t yy_base[279] =
    {   0,
        0,    0,  519,  833,   50,  833,  459,   48,  833,   51,
      833,  833,  833,  833,  833,  833,  426,  391,   43,  348,
      833,   40,  833,  281,   52,   59,   61,   60,   79,   77,
       70,   88,   81,   90,   39,   94,  113,  130,  117,  833,
      833,  158,   65,  833,   66,   68,  833,   71,   72,  150,
       82,    0,  142,  144,  833,  833,  833,  833,   80,  128,
      142,  151,  254,  164,  166,  167,  147,  195,  114,  178,
      122,  165,  194,  183,  201,  198,  192,  215,  223,   53,
      227,  134,  225,  231,  833,  233,   32,  234,  127,  216,
      245,  246,  244,  260,  251,  276,  282,  224,  266,  274,

      833,  291,   69,  279,  295,  311,  339,  249,  252,  245,
      295,    0,  320,  278,  833,  336,  270,  228,  302,  307,
      352,  303,  313,  275,  340,  346,  305,  363,  341,  367,
      366,  360,  833,  372,  388,  361,  381,  833,  362,  382,
      392,  400,  833,  417,  378,  421,  403,  420,  399,  408,
      424,  425,  419,  833,  435,  426,  437,  438,  446,  398,
      458,  457,  833,  454,  464,  471,  477,  472,  470,  482,
      510,  334,  479,  413,  508,  220,  512,  478,  515,  490,
      526,  521,  833,  527,  494,  542,  833,  543,  525,  551,
      506,  540,  545,  560,  577,  833,  833,  833,  578,  833,

      580,  833,  833,  561,  558,  571,  576,  585,  564,  586,
      589,  604,  833,  611,  591,  616,  600,  640,  613,  833,
      144,  641,  833,  642,  621,  624,  658,  550,  651,  833,
      664,  635,  672,  647,  668,  833,  678,  582,  648,  670,
      677,  654,  676,  682,  698,  712,  689,  715,  833,  702,
      695,  721,  102,  733,  700,  703,  708,  729,  706,  735,
      745,  833,  755,  833,  757,  833,  763,  833,  833,  833,
      833,  833,  833,  814,  819,  822,  827,   78
    } ;

static const flex_int16_t yy_def[279] =
    {   0,
      273,    1,  273,  273,  273,  273,  273,  274,  273,  275,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,   34,   26,   34,  276,   34,  273,
      273,  273,  273,  273,  274,  274,  273,  275,  275,  275,
      273,  277,  273,  273,  273,  273,  273,  273,  273,  276,
      276,   34,  278,  273,  276,  276,  273,  276,  273,  276,
      273,  276,  276,  273,  276,   34,  273,  276,  276,  273,
      276,  273,  276,  276,  273,  276,  273,  276,  273,   26,
      276,  276,  273,   34,  273,  276,  276,  273,  273,  273,

      273,  273,  273,  273,  273,  273,  273,  274,  275,  273,
      273,  277,  273,  276,  273,  276,  273,  278,  278,  273,
      276,  273,  276,  273,  273,   34,  273,  276,  273,   26,
      273,  276,  273,  273,  276,  273,  276,  273,  273,   26,
      273,  276,  273,  276,  273,  276,  273,  276,  273,   26,
      273,  273,  276,  273,  276,  273,  276,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  276,  273,  273,  273,  276,  273,   26,  273,
      273,  276,  273,  276,  273,  276,  273,   26,  273,  276,
      273,   34,  273,  276,  276,  273,  273,  273,  276,  273,

      276,  273,  273,   26,  273,   26,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  276,  273,
      273,  276,  273,  276,  273,  273,  276,  273,  276,  273,
      276,  273,  276,  273,  276,  273,  276,  273,  273,  273,
      273,  273,  273,  273,  273,  276,  273,  276,  273,   34,
      273,  276,  273,  276,  273,  273,  273,  273,  273,  273,
      276,  273,  276,  273,  276,  273,  276,  273,  273,  273,
      273,  273,    0,  273,  273,  273,  273,  273
    } ;

static const flex_int16_t yy_nxt[885] =
    {   0,
        4,    5,    6,    7,    5,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   19,   20,   21,
       22,   23,   24,   25,   26,   27,   28,   29,   30,   31,
       31,   32,   31,   31,   31,   33,   34,   35,   36,   31,
       37,   31,   38,   39,   31,   40,   41,    4,   29,   36,
       42,   43,   46,   47,   43,   49,   59,   53,   50,   54,
       54,   56,   57,   59,   59,   59,   43,   60,  145,   43,
      108,   47,   46,   47,   59,  109,   49,   86,   50,   50,
      119,   59,  145,   59,   59,   59,   65,   61,   86,   87,
       62,   68,   59,  141,   59,   66,   70,   63,  110,  111,

       75,   62,   64,  141,   63,   63,   63,   65,  131,   67,
       71,   69,   72,   76,   73,   63,   78,   81,   83,  131,
      273,   88,   63,   79,   63,   63,   63,   77,   84,   74,
       60,   82,   59,   63,   59,   63,  266,  127,   80,   84,
       85,   60,   88,   90,   89,   60,   59,   96,  221,   91,
      147,   92,  266,   94,  109,   97,  113,   50,   53,   51,
       54,   54,   92,   93,  127,  129,   97,   98,  114,   59,
       59,   59,  129,   63,  143,   63,  122,  147,  273,   60,
       95,   99,   59,  124,  143,  100,  101,   63,  102,  116,
      115,  103,  115,  104,  105,  121,  106,  125,   59,   59,

      116,  117,  117,  123,  130,   59,  100,  106,  107,  133,
       63,   63,   63,  117,  120,  131,  122,  124,  126,   59,
      132,  128,  131,   63,  221,  136,   60,   59,  129,   59,
      138,   59,  118,  134,  135,   59,  137,   59,   59,   63,
       63,  138,  139,  148,  133,  127,   63,  137,  138,   59,
       59,  136,   60,  108,   47,  159,  109,  146,  118,   50,
       63,  110,  110,  140,  148,  273,  149,  142,   63,  144,
       63,  149,   63,  141,  159,  273,   63,  143,   63,   63,
       59,  273,   59,  145,  147,  151,   59,  150,   60,  154,
       63,   63,  149,  174,  152,  273,  151,  147,  153,  136,

      154,  154,   58,  122,  154,  163,  175,  155,  180,  153,
      154,  110,  111,  157,  127,  154,  160,   59,  149,  141,
      174,   63,  156,   63,  161,  180,  156,   63,  273,  164,
      174,  124,  158,  138,  178,  143,  172,  172,  129,  149,
       59,  162,  158,  183,  138,  165,  179,  145,  176,  117,
      172,  172,  151,  178,  183,  183,   59,  174,   63,  173,
      117,  166,  167,  180,   59,  163,  149,   59,  122,   55,
      159,  178,  136,  180,   60,  168,  185,  169,  131,  170,
      151,   63,  129,  177,  182,   59,  174,  149,  169,  171,
      181,  185,   59,  187,  186,  182,  183,   63,  184,  187,

      189,  189,  178,   60,   59,   63,   52,  193,   63,  190,
      273,  189,  189,  185,  187,  186,  187,  187,   60,  191,
      187,   59,  187,   59,   59,   59,   63,  188,  193,  197,
      190,  273,  191,   63,  200,  201,  198,  189,  189,   59,
      191,   59,  191,   51,   60,   63,  192,  194,  189,  200,
      273,  202,  202,  196,  195,  199,  201,  220,  202,  205,
      200,   44,   63,  220,   63,   63,   63,  193,  204,  273,
      200,  196,  202,  202,  202,  203,  205,  206,  207,  205,
       63,  191,   63,   59,  197,  205,  207,  207,  207,  178,
      205,  198,  200,  174,  174,  183,  208,  180,  202,  185,

      193,  193,  191,  197,  191,  180,  183,  210,  209,  191,
      198,  207,  175,  223,  211,  183,   59,  225,  273,  202,
      174,  212,  214,  219,   63,   59,  183,  213,  223,  220,
      191,   59,  191,  174,  228,  232,  197,  215,  225,  193,
      225,  178,  224,  216,  228,  217,   59,  222,  183,  189,
      207,   60,  230,  225,  176,   59,  232,   63,  215,  183,
      218,  223,  223,  224,   59,  225,   63,  227,   60,  273,
      229,  273,   63,  230,  225,  230,  226,  228,  233,   60,
      231,   59,   59,  234,   59,  236,  249,   63,  235,  233,
      234,  229,  273,  230,  234,  234,   63,   60,  237,  223,

      249,  232,  273,  238,  273,   63,  236,   60,  236,  235,
      273,  236,  239,  236,  223,  255,  225,   59,  273,  237,
      232,  238,   63,   63,  238,   63,  238,  273,  273,  228,
      273,  238,  255,  239,  236,  239,  236,  225,  225,  240,
      228,  232,  234,  243,  247,   59,   59,  247,  220,  234,
      228,  273,  238,  234,  241,   59,  273,  273,   63,  225,
      234,  242,   59,  273,  243,  246,  243,  244,   59,  232,
      253,  247,   59,  251,  247,  223,   59,  258,  234,  273,
      228,  255,   59,  251,  220,  251,   63,   63,  244,  234,
      245,  273,  247,  247,  248,  252,   63,  253,  255,  247,

      253,  273,  250,   63,  258,  247,  249,  273,  249,   63,
      255,  254,  250,   63,  251,  255,   59,   63,  273,   59,
      256,  258,  253,   63,  262,   59,  247,  257,  255,  273,
       60,  255,  259,  264,  249,  268,  251,   59,  262,  262,
      263,  271,  266,  268,  264,  264,  251,  261,  260,   59,
      268,  263,  264,  262,  273,  265,  271,   63,  269,   59,
       63,   59,  262,  266,  262,  273,   63,   59,  267,  266,
      271,  266,  273,  264,  273,  273,  273,  273,   63,  270,
      273,  273,  273,  268,  264,  272,  273,  273,  273,  273,
       63,  273,  273,  273,  273,  273,  273,  273,  273,  273,

       63,  273,   63,  273,  273,  273,  273,  273,   63,  273,
      273,  273,  273,  273,   45,  273,   45,   45,   45,   48,
      273,   48,  273,   48,   60,  273,   60,  112,  273,  112,
      112,  112,    3,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273
    } ;

static const flex_int16_t yy_chk[885] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    8,    8,    5,   10,   25,   19,   10,   19,
       19,   22,   22,   26,   28,   27,   43,   35,   87,   43,
       45,   45,   46,   46,   31,   48,   49,   35,   48,   49,
      278,   30,   87,   29,   59,   33,   26,   25,   35,   35,
       25,   27,   32,   80,   34,   26,   28,   25,   51,   51,

       30,   25,   25,   80,   26,   28,   27,   26,  103,   26,
       28,   27,   29,   30,   29,   31,   32,   33,   34,  103,
       31,   36,   30,   32,   29,   59,   33,   30,   34,   29,
       36,   33,   60,   32,   38,   34,  253,   69,   32,   34,
       34,   37,   36,   37,   36,   39,   61,   39,  221,   37,
       89,   37,  253,   38,   50,   39,   53,   50,   54,   53,
       54,   54,   37,   37,   69,   71,   39,   39,   61,   72,
       65,   66,   71,   60,   82,   38,   67,   89,   60,   62,
       38,   42,   70,   67,   82,   42,   42,   61,   42,   62,
       64,   42,   61,   42,   42,   65,   42,   67,   73,   68,

       62,   62,   64,   66,   72,   75,   42,   42,   42,   74,
       72,   65,   66,   64,   64,   72,   65,   66,   68,   78,
       73,   70,   74,   70,  176,   77,   76,   79,   70,   83,
       77,   81,  118,   74,   75,   84,   76,   86,   88,   73,
       68,   77,   77,   90,   73,   68,   75,   76,   76,   91,
       92,   75,   90,  108,  108,   98,  109,   88,   63,  109,
       78,  110,  110,   79,   90,   78,   90,   81,   79,   86,
       83,   93,   81,   79,   98,   83,   84,   81,   86,   88,
       96,   84,  114,   86,   88,   93,   97,   92,   94,   95,
       91,   92,   93,  117,   93,   91,   92,  100,   94,   99,

       95,   95,   24,  100,   99,  104,  119,   96,  124,   94,
       94,  111,  111,   97,  102,   99,   99,  123,  102,  104,
      117,   96,  102,  114,  100,  124,   96,   97,  114,  104,
      120,  105,   97,  105,  122,  105,  113,  113,  105,  102,
      116,  102,  106,  127,  105,  105,  123,  106,  119,  106,
      172,  172,  106,  122,  127,  127,  121,  120,  123,  116,
      106,  106,  107,  123,  132,  107,  107,  128,  107,   20,
      107,  125,  107,  125,  126,  107,  129,  107,  107,  107,
      107,  116,  107,  121,  126,  137,  116,  107,  107,  107,
      125,  129,  135,  131,  130,  126,  126,  121,  128,  134,

      136,  139,  121,  130,  142,  132,   18,  145,  128,  140,
      132,  136,  139,  128,  131,  130,  131,  130,  140,  141,
      134,  144,  134,  153,  148,  146,  137,  135,  145,  147,
      140,  137,  140,  135,  149,  150,  147,  160,  135,  155,
      141,  157,  141,   17,  150,  142,  144,  146,  160,  149,
      142,  151,  152,  147,  146,  148,  150,  174,  150,  156,
      152,    7,  144,  174,  153,  148,  146,  144,  155,  153,
      148,  146,  151,  152,  151,  152,  156,  157,  158,  159,
      155,  164,  157,  173,  161,  155,  159,  157,  158,  161,
      162,  161,  162,  169,  166,  162,  159,  165,  166,  165,

      166,  168,  164,  167,  164,  168,  162,  162,  161,  170,
      167,  166,  175,  178,  165,  167,  177,  180,    3,  166,
      169,  166,  168,  173,  173,  182,  167,  167,  178,  173,
      170,  184,  170,  171,  185,  191,  171,  171,  180,  171,
      180,  171,  179,  171,  185,  171,  186,  177,  171,  171,
      171,  179,  189,  181,  175,  190,  191,  177,  171,  171,
      171,  181,  177,  179,  194,  179,  182,  184,  192,    0,
      188,  182,  184,  189,  181,  189,  181,  184,  192,  188,
      190,  195,  199,  193,  201,  205,  228,  186,  204,  192,
      192,  188,  186,  188,  193,  193,  190,  204,  206,  209,

      228,  190,    0,  207,    0,  194,  205,  206,  205,  204,
      194,  204,  208,  210,  209,  238,  211,  219,    0,  206,
      215,  206,  195,  199,  207,  201,  207,  195,  199,  211,
      201,  212,  238,  208,  210,  208,  210,  211,  214,  211,
      217,  215,  212,  216,  225,  222,  224,  226,  212,  214,
      217,    0,  212,  212,  212,  229,    0,    0,  219,  214,
      214,  214,  227,  219,  216,  224,  216,  218,  231,  218,
      234,  225,  235,  232,  226,  218,  233,  242,  218,    0,
      218,  239,  237,  232,  218,  232,  222,  224,  218,  218,
      218,  222,  224,  240,  227,  233,  229,  234,  239,  243,

      241,  229,  231,  227,  242,  244,  240,    0,  227,  231,
      241,  237,  231,  235,  231,  244,  246,  233,  235,  248,
      240,  245,  233,  237,  247,  252,  243,  241,  237,    0,
      250,  245,  244,  251,  245,  255,  245,  254,  256,  247,
      250,  259,  257,  257,  251,  251,  245,  246,  245,  261,
      255,  250,  250,  256,    0,  252,  259,  246,  257,  263,
      248,  265,  246,  258,  258,  248,  252,  267,  254,  260,
      260,  252,    0,  260,    0,    0,    0,    0,  254,  258,
        0,    0,    0,  254,  260,  260,    0,    0,    0,    0,
      261,    0,    0,    0,    0,  261,    0,    0,    0,    0,

      263,    0,  265,    0,    0,  263,    0,  265,  267,    0,
        0,    0,    0,  267,  274,    0,  274,  274,  274,  275,
        0,  275,    0,  275,  276,    0,  276,  277,    0,  277,
      277,  277,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[61] =
    {   0,
1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "Z1UTQFZ5.l"
#line 2 "Z1UTQFZ5.l"
#include "y.tab.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define MAX_SYMBOLS 256 // You need to define how many symbols you expect

// line number, lexeme, and tokens
typedef struct {
    int line_num;     // Line number in the source file
    char *lexeme;     // The actual text (string) of the token
    char *token;      // Token type
} SymbolTable;

SymbolTable table[MAX_SYMBOLS]; // Fixed size for simplicity
int line = 1;
int table_size = 0;

void add_to_table(const char* lex, const char* tok) {
    
    table[table_size].line_num = line;
    table[table_size].lexeme = strdup(lex); // strdup allocates and copies
    table[table_size].token = strdup(tok);
    table_size++;

    //printf("\n lines = %d\n", line);
}

#line 784 "lex.yy.c"
#line 785 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 35 "Z1UTQFZ5.l"


#line 1005 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 274 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 833 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 37 "Z1UTQFZ5.l"
{ 
    //printf("\n SKIPPING Newlines"); 
    line++; 
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 42 "Z1UTQFZ5.l"
{ 
    //printf("\n SKIPPING Spaces"); /* Skip whitespace. */ 
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 46 "Z1UTQFZ5.l"
{ 

    //printf("\nComment found"); 
    add_to_table(yytext, "Comment");  
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 52 "Z1UTQFZ5.l"
{
    
    //add_to_table(yytext, "Message");
    //printf("\nLex : saw msg : %s", yytext);
    yylval.t.v.string = strdup(yytext);
    return T_STRING;
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 60 "Z1UTQFZ5.l"
{
    //printf("\nsaw quotes");
    //add_to_table(yytext, "Message");
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 65 "Z1UTQFZ5.l"
{

    //printf("\nlex: Of: %s", yytext);
    return T_OF;
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 71 "Z1UTQFZ5.l"
{ 
    
    //printf("\nOperator"); 
    add_to_table(yytext, "Operator");
    return T_AND;
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 78 "Z1UTQFZ5.l"
{ 
    //printf("\nOperator"); 
    add_to_table(yytext, "Operator");
    return T_OR;
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 84 "Z1UTQFZ5.l"
{ 
    //printf("\nLex: NOT Operator"); 
    add_to_table(yytext, "Operator");
    return T_NOT;
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 90 "Z1UTQFZ5.l"
{

    //printf("\nProgram begins"); 
    add_to_table(yytext, "Keyword");
    return T_PROGRAM;
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 97 "Z1UTQFZ5.l"
{ 
    //printf("\nSaw var"); 
    add_to_table(yytext, "Keyword");
    return T_VAR;
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 103 "Z1UTQFZ5.l"
{ 

    //printf("\nInteger found"); 
    add_to_table(yytext, "Keyword");
    return T_INTEGER; 
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 110 "Z1UTQFZ5.l"
{ 
    //printf("\nInteger found"); 
    add_to_table(yytext, "Keyword");
    return T_INTEGER; 
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 116 "Z1UTQFZ5.l"
{ 
    //printf("\nReal");
    //yylval.string = strdup("real"); 
    add_to_table(yytext, "Keyword"); 
    return T_REAL;
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 123 "Z1UTQFZ5.l"
{ 
    //printf("\nChar"); 
    //yylval.string = strdup("char");
    add_to_table(yytext, "Keyword");
    return T_CHAR;
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 130 "Z1UTQFZ5.l"
{ 
    //printf("\nboolean"); 
    //yylval.string = strdup("boolean");
    add_to_table(yytext, "Keyword"); 
    return T_BOOLEAN;
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 137 "Z1UTQFZ5.l"
{ 
    //printf("\nboolean"); 
    add_to_table(yytext, "Keyword"); 
    return T_FOR;
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 143 "Z1UTQFZ5.l"
{

    add_to_table(yytext, "Keyword"); 
    return T_IF;
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 149 "Z1UTQFZ5.l"
{

    add_to_table(yytext, "Keyword"); 
    return T_ELSE;
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 155 "Z1UTQFZ5.l"
{

    add_to_table(yytext, "Keyword"); 
    return T_THEN;
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 161 "Z1UTQFZ5.l"
{ 
    //printf("\nboolean"); 
    add_to_table(yytext, "Keyword"); 
    return T_DO;
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 167 "Z1UTQFZ5.l"
{
    add_to_table(yytext, "Keyword"); 
    return T_DOWNTO;
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 172 "Z1UTQFZ5.l"
{ 
    //printf("\nboolean"); 
    add_to_table(yytext, "Keyword"); 
    return T_TO;
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 178 "Z1UTQFZ5.l"
{ 
    //printf("\nboolean"); 
    add_to_table(yytext, "Keyword"); 
    return T_WHILE;
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 184 "Z1UTQFZ5.l"
{ 
    //printf("\nboolean"); 
    add_to_table(yytext, "Keyword"); 
    return T_ARRAY;
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 190 "Z1UTQFZ5.l"
{ 

    //printf("\nbegin"); 
    add_to_table(yytext, "Keyword"); 
    return T_BEGIN;
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 197 "Z1UTQFZ5.l"
{ 

    //printf("\nend"); 
    add_to_table(yytext, "Keyword");
    return T_END;
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 204 "Z1UTQFZ5.l"
{  
    //printf("\nWrite"); 
    add_to_table(yytext, "Keyword");
    return T_write;
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 210 "Z1UTQFZ5.l"
{  
    //printf("\nWrite"); 
    add_to_table(yytext, "Keyword");
    return T_write;
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 216 "Z1UTQFZ5.l"
{  
    //printf("\nren"); 
    add_to_table(yytext, "Keyword");
    return T_READ;
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 222 "Z1UTQFZ5.l"
{
    add_to_table(yytext, "Keyword");
    return T_TRUE;
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 227 "Z1UTQFZ5.l"
{
    add_to_table(yytext, "Keyword");
    return T_FALSE;
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 232 "Z1UTQFZ5.l"
{ 
    //printf("\nLex:Identifier: %s", yytext); 
    yylval.t.v.string = strdup(yytext);
    add_to_table(yytext, "Identifier"); 
    return ID;
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 239 "Z1UTQFZ5.l"
{
    yylval.t.v.string = strdup(yytext);
    return ArrElement;
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 244 "Z1UTQFZ5.l"
{ 
                yylval.t.v.cval=yytext[0]; //printf("\nLex : Reading Char"); 
                return CHAR; 
            }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 249 "Z1UTQFZ5.l"
{ 
    //printf("\nLex: yylval.ival = %d", yylval.t.v.ival);
    yylval.t.v.ival = atoi(yytext);
    return NUM; 
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 255 "Z1UTQFZ5.l"
{ 
    // Debug print the found range
    //printf("\nLex : Found RANGE %s", yytext);
    add_to_table(yytext, "Seperator");

    char *ptr = yytext;
    int lower = atoi(ptr);  // Convert starting numbers to int
    while (*ptr && *ptr != '.') ptr++; // Move pointer to the first dot in ".."

    if (*ptr == '.') {
        ptr += 2; // Move past the ".." to start of upper range
        int upper = atoi(ptr); // Convert ending numbers to int

        yylval.t.v.c1 = lower; // Store lower bound in yylval.t.v.c1
        yylval.t.v.c2 = upper; // Store upper bound in yylval.t.v.c2

        // Additional debug prints to verify correct parsing
        //printf("\nLex : lower = %d", lower);
        //printf("\nLex : higher = %d", upper);

        int size = upper - lower + 1; // Compute size of the array
        if (size > 0) {
            yylval.t.v.ival = size; // Store the size in yylval to use in your parser
            add_to_table(yytext, "Range");
            return RANGE; // Return the RANGE token
        } else {
            fprintf(stderr, "Invalid array range: %s\n", yytext);
            return -1; // Return an error token or handle as needed
        }
    } else {
        fprintf(stderr, "Invalid range format: %s\n", yytext);
        return -1; // Return an error token or handle as needed
    }
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 290 "Z1UTQFZ5.l"
{ 
    //printf("\nSeperator"); 
    add_to_table(yytext, "Seperator");
    return DOT;
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 296 "Z1UTQFZ5.l"
{yylval.t.v.fval=atof(yytext);return FLOAT;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 298 "Z1UTQFZ5.l"
{
    //printf("\nSeperator"); 
    add_to_table(yytext, "Seperator");
    return COMMA;
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 304 "Z1UTQFZ5.l"
{ 
    //printf("\nSeperator"); 
    add_to_table(yytext, "Seperator");
    return SC;
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 310 "Z1UTQFZ5.l"
{ 
    //printf("\nColon"); 
    add_to_table(yytext, "Seperator");
    return COL;
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 316 "Z1UTQFZ5.l"
{ 
    //printf("\nSeperator"); 
    add_to_table(yytext, "Seperator");
    return OB;
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 322 "Z1UTQFZ5.l"
{ 
    //printf("\nSeperator"); 
    add_to_table(yytext, "Seperator");
    return CB;
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 328 "Z1UTQFZ5.l"
{ 
    //printf("\nAssignment operator"); 
    add_to_table(yytext, "Operator");
    return AS;
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 334 "Z1UTQFZ5.l"
{ 
    //printf("\nOperator"); 
    add_to_table(yytext, "Operator");
    return PLUS;
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 340 "Z1UTQFZ5.l"
{ 
    //printf("\nOperator"); 
    add_to_table(yytext, "Operator");
    return MINUS;
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 346 "Z1UTQFZ5.l"
{ 
    //printf("\nOperator"); 
    add_to_table(yytext, "Operator");
    return DIV;
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 352 "Z1UTQFZ5.l"
{ 
    //printf("\nOperator"); 
    add_to_table(yytext, "Operator");
    return MUL;
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 358 "Z1UTQFZ5.l"
{ 
    //printf("\nOperator"); 
    add_to_table(yytext, "Operator");
    return REM;
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 364 "Z1UTQFZ5.l"
{ 
    //printf("\nOperator"); 
    add_to_table(yytext, "Operator");
    return EQUAL;
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 370 "Z1UTQFZ5.l"
{ 
    //printf("\nOperator"); 
    add_to_table(yytext, "Operator");
    return NEQ;
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 376 "Z1UTQFZ5.l"
{ 
    //printf("\nOperator"); 
    add_to_table(yytext, "Operator");
    return LT;
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 382 "Z1UTQFZ5.l"
{ 
    //printf("\nOperator"); 
    add_to_table(yytext, "Operator");
    return GT;
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 388 "Z1UTQFZ5.l"
{ 
    //printf("\nOperator"); 
    add_to_table(yytext, "Operator");
    return LE;
}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 394 "Z1UTQFZ5.l"
{ 
    //printf("\nOperator"); 
    add_to_table(yytext, "Operator");
    return GE;
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 400 "Z1UTQFZ5.l"
{
    add_to_table(yytext, "Seperator");
    return SOB;
}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 405 "Z1UTQFZ5.l"
{
    add_to_table(yytext, "Seperator");
    return SCB;
}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 410 "Z1UTQFZ5.l"
{ 
    //printf("\nsaw something");
    /* Handle other tokens */ 
}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 415 "Z1UTQFZ5.l"
ECHO;
	YY_BREAK
#line 1633 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 274 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 274 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 273);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 415 "Z1UTQFZ5.l"

